export const AUTHLOADING_REGISTER = "AUTHLOADING_REGISTER"
export const AUTHERROR_REGISTER = "AUTHERROR_REGISTER"
export const AUTHREGISTER_INIT = "AUTHREGISTER_INIT"

export const AUTHLOADING_LOGIN = "AUTHLOADING_LOGIN"
export const AUTHERROR_LOGIN = "AUTHERROR_LOGIN"
export const AUTHLOGIN_INIT = "AUTHLOGIN_INIT"

export const AUTHLOADING_OTP = "AUTHLOADING_OTP"
export const AUTHERROR_OTP = "AUTHERROR_OTP"
export const AUTHOTP_INIT = "AUTHOTP_INIT"
export const AUTHTAKETOKEN = "AUTHTAKETOKEN"

export const LOGOUTUSER = "LOGOUTUSER"

